version: "3.4"

services:
  ldap:
    build: ./ldap-base/
    image: czhelp/ldap-base
    container_name: ldap
    ports:
      - "10389:389"
      - "10636:636"
    environment:
      - LDAP_DOMAIN=example.com
      - LDAP_PASSWORD=secret
    networks:
      - net
    volumes:
      - ldap_conf:/etc/ldap/slapd.d
      - ldap_data:/var/lib/ldap

  midpoint:
    build: ./mp-base/
    image: czhelp/mp-base
    container_name: midpoint
    ports:
      - "8080:8080"
    networks:
      - net
    volumes:
     - midpoint_home:/opt/midpoint/var


networks:
  net:    
    driver: bridge

volumes:
  midpoint_home:
    name: midpoint_home
  ldap_conf:
    name: ldap_conf
  ldap_data:
    name: ldap_data
