FROM evolveum/midpoint

LABEL maintainer=info@evolveum.com

ADD container-book-midpoint_files/rms.csv /opt/midpoint/var/resources/

ADD  https://raw.githubusercontent.com/Evolveum/midpoint-samples/master/samples/book/2/resource-crm.xml \
 https://raw.githubusercontent.com/Evolveum/midpoint-samples/master/samples/book/5/resource-openldap.xml \
 https://raw.githubusercontent.com/Evolveum/midpoint-samples/master/samples/book/7/role-business-analyst.xml \
 container-book-midpoint_files/role-clerk.xml \
 container-book-midpoint_files/role-supervisor.xml \
 container-book-midpoint_files/resource-csv-rms.xml \
 container-book-midpoint_files/z-001-task-update-resource-crm_host-chapter7.xml \
 container-book-midpoint_files/z-002-task-update-resource-ldap_host-chapter7.xml \
 container-book-midpoint_files/z-003-task-testResource-resource-rms.xml \
 /opt/midpoint/var/post-initial-objects/
