FROM evolveum/midpoint:latest

LABEL maintainer=info@evolveum.com

ADD https://raw.githubusercontent.com/Evolveum/midpoint-samples/master/samples/book/5/hr.csv /opt/midpoint/var/resources/
ADD https://raw.githubusercontent.com/Evolveum/midpoint-samples/master/samples/book/5/resource-csv-hr.xml \
 https://raw.githubusercontent.com/Evolveum/midpoint-samples/master/samples/book/5/resource-openldap.xml \
 container-book-midpoint_files/z-001-task-update-resource-ldap_host-chapter5.xml \
 container-book-midpoint_files/z-002-task-testResource-resource-csv.xml \
 /opt/midpoint/var/post-initial-objects/

