FROM evolveum/midpoint

LABEL maintainer=info@evolveum.com

ADD https://raw.githubusercontent.com/Evolveum/midpoint-samples/master/samples/book/2/hr.csv /opt/midpoint/var/resources/
ADD https://raw.githubusercontent.com/Evolveum/midpoint-samples/master/samples/book/2/resource-csv-hr.xml \
 https://raw.githubusercontent.com/Evolveum/midpoint-samples/master/samples/book/2/resource-openldap.xml \
 https://raw.githubusercontent.com/Evolveum/midpoint-samples/master/samples/book/2/resource-crm.xml \
 https://raw.githubusercontent.com/Evolveum/midpoint-samples/master/samples/book/2/resource-portal.xml \
 https://raw.githubusercontent.com/Evolveum/midpoint-samples/master/samples/book/5/task-hr-import.xml \
 container-book-midpoint_files/post-initial-objects/* \
 /opt/midpoint/var/post-initial-objects/
